spring.application.name=marketplace-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=never

server.port=8667
logging.level.com.example.marketplace=DEBUG

# JWT
jwt.secret=dGhpcy1pcy1hLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS1mb3ItbWFya2V0cGxhY2U=
jwt.expiration=86400000

# Настройки загрузки файлов (multipart/form-data).
# max-file-size  — максимальный размер одного файла.
# max-request-size — максимальный размер всего запроса (файл + метаданные).
# Значение 3MB для запроса: 2MB файл + ~1MB на заголовки и другие поля формы.
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB
